version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: avito_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    image: migrate/migrate:4
    container_name: avito_migrator
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/usr/local/bin/migrate"]
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]

  app:
    container_name: avito_pr_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"

volumes:
  postgres_data:
